title: EAT AND REPEAT
author: Purvi Darekar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 A foodie is a person who has an ardent or refined interest in food and who eats food not only out of hunger but also as a hobby.
 The terms "gastronome" and "gourmet" define the same thing, i.e. a person who enjoys food for pleasure.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
